language: ruby
rvm:
    - 1.8.7
    - 1.9.3
    - '2.1'
script: 'rake spec'
before_install:
    - mkdir -p ~/.facter/facts.d
    - echo "user_ssh_pubkey=not_a_user" >> ~/.facter/facts.d/user_ssh_pubkey.txt
env:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="3"
gemfile: .gemfile
notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - rvm: 1.9.3
        - rvm: '2.1'
    exclude:
        - rvm: '2.1'
          env: PUPPET_VERSION="~> 2.7.0"
