language: ruby
rvm:
    - 1.8.7
    - 1.9.3
    - '2.1'
script: 'rake spec'
env:
    - FACTER_VERSION="1"
    - FACTER_VERSION="2"
gemfile: .gemfile
notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - rvm: 1.9.3
        - rvm: '2.1'
