language: ruby
rvm:
  - 1.8.7
  - 2.0.0
script: 'rake spec'
env:
  global:
    - SPEC_OPTS="-fd"
  matrix:
    - PUPPET_VERSION="~> 2.7.0"
    - PUPPET_VERSION="~> 3"
gemfile: .gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.0.0
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
notifications:
  email: false
before_script:
    - mkdir -p ~/.facter/facts.d
    - echo "user_ssh_pubkey=not_a_user" >> ~/.facter/facts.d/user_ssh_pubkey.txt
    - facter user_ssh_pubkey
